name: Deploy To GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - "index.html"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # I - Checkout do repositorio
            - name: Checkout repository
              uses: actions/checkout@v3
            
            # II - Configurando o Pages
            - name: Setup Pages
              uses: actions/configure-pages@v5

            # III - Upload do artefato
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: .

            # IV - Deploy no Pages
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
