name: Deploy To GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - "index.html"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 1 - Configura a checagem do repositorio
            - name: Checkout repository
              uses: actions/checkout@v3
            
            # 2 - Configura o GitHub Pages
            - name: Setup Pages
              uses: actions/configure-pages@v5

            # 3 - Faz upload do artefato (nesse caso o proprio index.html)
            - name: Upload Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: .

            # 4 - Faz o deploy do GitHub Pages
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
